
"""
Create a program that will play the “cows and bulls” game with the user. The game works like this:
Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the
user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed
correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many
“cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track
of the number of guesses the user makes throughout teh game and tell the user at the end.
Say the number generated by the computer is 1038. An example interaction could look like this:
  Welcome to the Cows and Bulls Game!
  Enter a number:
  >>> 1234
  2 cows, 0 bulls
  >>> 1250
  1 cow, 1 bull
  ...
"""


#couple of important lines of code to use
#
#import random
#
#number = str(random.randint(0,9999)) #random 4 digit number
#userGuess = input("Give me your best guess!")  #returns a string
#print("Let's play a game of Cowbull!")  # explanation
#print("I will generate a number, and you have to guess the numbers one digit at a time.")
#print("For every number in the wrong place, you get a cow. For every one in the right place, you get a bull.")
#print("The game ends when you get 4 bulls!")
#print("Type exit at any prompt to exit.")

import random
number = str(random.randint(0,9999)) #random 4 digit number
#number = '1235'

KeepGoing = True


while KeepGoing:
    userGuess = input("Give me your best guess! ")  #returns a string
    cows = 0
    bulls = 0

    if userGuess == 'exit':
        break

    if len(userGuess) != 4:
        print("enter 4 numbers...")
    elif not userGuess.isdigit():
        print("  numbers only...")
    else:
        for i in range(4):
            if number[i] == userGuess[i]:
                bulls += 1
            else:
                if number[i] == userGuess[0]:
                    cows += 1
                if number[i] == userGuess[1]:
                    cows += 1
                if number[i] == userGuess[2]:
                    cows += 1
                if number[i] == userGuess[3]:
                    cows += 1

        print("Bulls: " + str(bulls) + " Cows: " + str(cows))

        if bulls == 4:
            print("you win!")
            break





