from setuptools import setup

setup(
    name='ACP',
    version='',
    packages=['venv.lib.python3.7.site-packages.cv2', 'venv.lib.python3.7.site-packages.cv2.data',
              'venv.lib.python3.7.site-packages.PIL', 'venv.lib.python3.7.site-packages.pip',
              'venv.lib.python3.7.site-packages.pip._vendor', 'venv.lib.python3.7.site-packages.pip._vendor.idna',
              'venv.lib.python3.7.site-packages.pip._vendor.pep517',
              'venv.lib.python3.7.site-packages.pip._vendor.pytoml',
              'venv.lib.python3.7.site-packages.pip._vendor.certifi',
              'venv.lib.python3.7.site-packages.pip._vendor.chardet',
              'venv.lib.python3.7.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.7.site-packages.pip._vendor.distlib',
              'venv.lib.python3.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.7.site-packages.pip._vendor.msgpack',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.pip._vendor.colorama',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.7.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.7.site-packages.pip._vendor.progress',
              'venv.lib.python3.7.site-packages.pip._vendor.requests',
              'venv.lib.python3.7.site-packages.pip._vendor.packaging',
              'venv.lib.python3.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.7.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.7.site-packages.pip._internal', 'venv.lib.python3.7.site-packages.pip._internal.cli',
              'venv.lib.python3.7.site-packages.pip._internal.req',
              'venv.lib.python3.7.site-packages.pip._internal.vcs',
              'venv.lib.python3.7.site-packages.pip._internal.utils',
              'venv.lib.python3.7.site-packages.pip._internal.models',
              'venv.lib.python3.7.site-packages.pip._internal.commands',
              'venv.lib.python3.7.site-packages.pip._internal.operations', 'venv.lib.python3.7.site-packages.ampy',
              'venv.lib.python3.7.site-packages.idna', 'venv.lib.python3.7.site-packages.pytz',
              'venv.lib.python3.7.site-packages.click', 'venv.lib.python3.7.site-packages.numpy',
              'venv.lib.python3.7.site-packages.numpy.ma', 'venv.lib.python3.7.site-packages.numpy.ma.tests',
              'venv.lib.python3.7.site-packages.numpy.doc', 'venv.lib.python3.7.site-packages.numpy.fft',
              'venv.lib.python3.7.site-packages.numpy.fft.tests', 'venv.lib.python3.7.site-packages.numpy.lib',
              'venv.lib.python3.7.site-packages.numpy.lib.tests', 'venv.lib.python3.7.site-packages.numpy.core',
              'venv.lib.python3.7.site-packages.numpy.core.tests', 'venv.lib.python3.7.site-packages.numpy.f2py',
              'venv.lib.python3.7.site-packages.numpy.f2py.tests', 'venv.lib.python3.7.site-packages.numpy.tests',
              'venv.lib.python3.7.site-packages.numpy.compat', 'venv.lib.python3.7.site-packages.numpy.compat.tests',
              'venv.lib.python3.7.site-packages.numpy.linalg', 'venv.lib.python3.7.site-packages.numpy.linalg.tests',
              'venv.lib.python3.7.site-packages.numpy.random', 'venv.lib.python3.7.site-packages.numpy.random.tests',
              'venv.lib.python3.7.site-packages.numpy.testing', 'venv.lib.python3.7.site-packages.numpy.testing.tests',
              'venv.lib.python3.7.site-packages.numpy.testing._private',
              'venv.lib.python3.7.site-packages.numpy.distutils',
              'venv.lib.python3.7.site-packages.numpy.distutils.tests',
              'venv.lib.python3.7.site-packages.numpy.distutils.command',
              'venv.lib.python3.7.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python3.7.site-packages.numpy.matrixlib',
              'venv.lib.python3.7.site-packages.numpy.matrixlib.tests',
              'venv.lib.python3.7.site-packages.numpy.polynomial',
              'venv.lib.python3.7.site-packages.numpy.polynomial.tests', 'venv.lib.python3.7.site-packages.pyowm',
              'venv.lib.python3.7.site-packages.pyowm.tiles', 'venv.lib.python3.7.site-packages.pyowm.utils',
              'venv.lib.python3.7.site-packages.pyowm.caches', 'venv.lib.python3.7.site-packages.pyowm.commons',
              'venv.lib.python3.7.site-packages.pyowm.agroapi10', 'venv.lib.python3.7.site-packages.pyowm.alertapi30',
              'venv.lib.python3.7.site-packages.pyowm.exceptions',
              'venv.lib.python3.7.site-packages.pyowm.abstractions',
              'venv.lib.python3.7.site-packages.pyowm.uvindexapi30',
              'venv.lib.python3.7.site-packages.pyowm.uvindexapi30.xsd',
              'venv.lib.python3.7.site-packages.pyowm.weatherapi25',
              'venv.lib.python3.7.site-packages.pyowm.weatherapi25.xsd',
              'venv.lib.python3.7.site-packages.pyowm.weatherapi25.cityids',
              'venv.lib.python3.7.site-packages.pyowm.weatherapi25.parsers',
              'venv.lib.python3.7.site-packages.pyowm.stationsapi30',
              'venv.lib.python3.7.site-packages.pyowm.stationsapi30.xsd',
              'venv.lib.python3.7.site-packages.pyowm.stationsapi30.parsers',
              'venv.lib.python3.7.site-packages.pyowm.pollutionapi30',
              'venv.lib.python3.7.site-packages.pyowm.pollutionapi30.xsd', 'venv.lib.python3.7.site-packages.scipy',
              'venv.lib.python3.7.site-packages.scipy.io', 'venv.lib.python3.7.site-packages.scipy.io.arff',
              'venv.lib.python3.7.site-packages.scipy.io.arff.tests', 'venv.lib.python3.7.site-packages.scipy.io.tests',
              'venv.lib.python3.7.site-packages.scipy.io.matlab',
              'venv.lib.python3.7.site-packages.scipy.io.matlab.tests',
              'venv.lib.python3.7.site-packages.scipy.io.harwell_boeing',
              'venv.lib.python3.7.site-packages.scipy.io.harwell_boeing.tests',
              'venv.lib.python3.7.site-packages.scipy.odr', 'venv.lib.python3.7.site-packages.scipy.odr.tests',
              'venv.lib.python3.7.site-packages.scipy._lib', 'venv.lib.python3.7.site-packages.scipy._lib.tests',
              'venv.lib.python3.7.site-packages.scipy.misc', 'venv.lib.python3.7.site-packages.scipy.misc.tests',
              'venv.lib.python3.7.site-packages.scipy.stats', 'venv.lib.python3.7.site-packages.scipy.stats.tests',
              'venv.lib.python3.7.site-packages.scipy.linalg', 'venv.lib.python3.7.site-packages.scipy.linalg.tests',
              'venv.lib.python3.7.site-packages.scipy.signal', 'venv.lib.python3.7.site-packages.scipy.signal.tests',
              'venv.lib.python3.7.site-packages.scipy.signal.windows', 'venv.lib.python3.7.site-packages.scipy.sparse',
              'venv.lib.python3.7.site-packages.scipy.sparse.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.dsolve',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.isolve',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.isolve.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.csgraph',
              'venv.lib.python3.7.site-packages.scipy.sparse.csgraph.tests',
              'venv.lib.python3.7.site-packages.scipy.cluster', 'venv.lib.python3.7.site-packages.scipy.cluster.tests',
              'venv.lib.python3.7.site-packages.scipy.fftpack', 'venv.lib.python3.7.site-packages.scipy.fftpack.tests',
              'venv.lib.python3.7.site-packages.scipy.ndimage', 'venv.lib.python3.7.site-packages.scipy.ndimage.tests',
              'venv.lib.python3.7.site-packages.scipy.spatial', 'venv.lib.python3.7.site-packages.scipy.spatial.tests',
              'venv.lib.python3.7.site-packages.scipy.spatial.transform',
              'venv.lib.python3.7.site-packages.scipy.spatial.transform.tests',
              'venv.lib.python3.7.site-packages.scipy.special', 'venv.lib.python3.7.site-packages.scipy.special.tests',
              'venv.lib.python3.7.site-packages.scipy.special._precompute',
              'venv.lib.python3.7.site-packages.scipy.optimize', 'venv.lib.python3.7.site-packages.scipy.optimize._lsq',
              'venv.lib.python3.7.site-packages.scipy.optimize.tests',
              'venv.lib.python3.7.site-packages.scipy.optimize._trlib',
              'venv.lib.python3.7.site-packages.scipy.optimize._shgo_lib',
              'venv.lib.python3.7.site-packages.scipy.optimize._trustregion_constr',
              'venv.lib.python3.7.site-packages.scipy.optimize._trustregion_constr.tests',
              'venv.lib.python3.7.site-packages.scipy.constants',
              'venv.lib.python3.7.site-packages.scipy.constants.tests',
              'venv.lib.python3.7.site-packages.scipy.integrate',
              'venv.lib.python3.7.site-packages.scipy.integrate._ivp',
              'venv.lib.python3.7.site-packages.scipy.integrate.tests',
              'venv.lib.python3.7.site-packages.scipy.interpolate',
              'venv.lib.python3.7.site-packages.scipy.interpolate.tests',
              'venv.lib.python3.7.site-packages.scipy._build_utils', 'venv.lib.python3.7.site-packages.dotenv',
              'venv.lib.python3.7.site-packages.pandas', 'venv.lib.python3.7.site-packages.pandas.io',
              'venv.lib.python3.7.site-packages.pandas.io.sas', 'venv.lib.python3.7.site-packages.pandas.io.json',
              'venv.lib.python3.7.site-packages.pandas.io.formats',
              'venv.lib.python3.7.site-packages.pandas.io.msgpack',
              'venv.lib.python3.7.site-packages.pandas.io.clipboard', 'venv.lib.python3.7.site-packages.pandas.api',
              'venv.lib.python3.7.site-packages.pandas.api.types',
              'venv.lib.python3.7.site-packages.pandas.api.extensions', 'venv.lib.python3.7.site-packages.pandas.core',
              'venv.lib.python3.7.site-packages.pandas.core.util', 'venv.lib.python3.7.site-packages.pandas.core.tools',
              'venv.lib.python3.7.site-packages.pandas.core.arrays',
              'venv.lib.python3.7.site-packages.pandas.core.dtypes',
              'venv.lib.python3.7.site-packages.pandas.core.sparse',
              'venv.lib.python3.7.site-packages.pandas.core.groupby',
              'venv.lib.python3.7.site-packages.pandas.core.indexes',
              'venv.lib.python3.7.site-packages.pandas.core.reshape',
              'venv.lib.python3.7.site-packages.pandas.core.internals',
              'venv.lib.python3.7.site-packages.pandas.core.computation',
              'venv.lib.python3.7.site-packages.pandas.util', 'venv.lib.python3.7.site-packages.pandas._libs',
              'venv.lib.python3.7.site-packages.pandas._libs.tslibs', 'venv.lib.python3.7.site-packages.pandas.tests',
              'venv.lib.python3.7.site-packages.pandas.tests.io',
              'venv.lib.python3.7.site-packages.pandas.tests.io.sas',
              'venv.lib.python3.7.site-packages.pandas.tests.io.json',
              'venv.lib.python3.7.site-packages.pandas.tests.io.parser',
              'venv.lib.python3.7.site-packages.pandas.tests.io.formats',
              'venv.lib.python3.7.site-packages.pandas.tests.io.msgpack',
              'venv.lib.python3.7.site-packages.pandas.tests.api', 'venv.lib.python3.7.site-packages.pandas.tests.util',
              'venv.lib.python3.7.site-packages.pandas.tests.frame',
              'venv.lib.python3.7.site-packages.pandas.tests.tools',
              'venv.lib.python3.7.site-packages.pandas.tests.arrays',
              'venv.lib.python3.7.site-packages.pandas.tests.arrays.sparse',
              'venv.lib.python3.7.site-packages.pandas.tests.arrays.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.arrays.categorical',
              'venv.lib.python3.7.site-packages.pandas.tests.dtypes',
              'venv.lib.python3.7.site-packages.pandas.tests.dtypes.cast',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.period',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.timedelta',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.timestamp',
              'venv.lib.python3.7.site-packages.pandas.tests.series',
              'venv.lib.python3.7.site-packages.pandas.tests.series.indexing',
              'venv.lib.python3.7.site-packages.pandas.tests.sparse',
              'venv.lib.python3.7.site-packages.pandas.tests.sparse.frame',
              'venv.lib.python3.7.site-packages.pandas.tests.sparse.series',
              'venv.lib.python3.7.site-packages.pandas.tests.tslibs',
              'venv.lib.python3.7.site-packages.pandas.tests.generic',
              'venv.lib.python3.7.site-packages.pandas.tests.groupby',
              'venv.lib.python3.7.site-packages.pandas.tests.groupby.aggregate',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.multi',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.period',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.datetimes',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.timedeltas',
              'venv.lib.python3.7.site-packages.pandas.tests.reshape',
              'venv.lib.python3.7.site-packages.pandas.tests.reshape.merge',
              'venv.lib.python3.7.site-packages.pandas.tests.tseries',
              'venv.lib.python3.7.site-packages.pandas.tests.tseries.offsets',
              'venv.lib.python3.7.site-packages.pandas.tests.indexing',
              'venv.lib.python3.7.site-packages.pandas.tests.indexing.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.indexing.multiindex',
              'venv.lib.python3.7.site-packages.pandas.tests.plotting',
              'venv.lib.python3.7.site-packages.pandas.tests.resample',
              'venv.lib.python3.7.site-packages.pandas.tests.extension',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.base',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.json',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.arrow',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.numpy_',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.decimal',
              'venv.lib.python3.7.site-packages.pandas.tests.internals',
              'venv.lib.python3.7.site-packages.pandas.tests.arithmetic',
              'venv.lib.python3.7.site-packages.pandas.tests.reductions',
              'venv.lib.python3.7.site-packages.pandas.tests.computation',
              'venv.lib.python3.7.site-packages.pandas.arrays', 'venv.lib.python3.7.site-packages.pandas.compat',
              'venv.lib.python3.7.site-packages.pandas.compat.numpy', 'venv.lib.python3.7.site-packages.pandas.errors',
              'venv.lib.python3.7.site-packages.pandas.tseries', 'venv.lib.python3.7.site-packages.pandas.plotting',
              'venv.lib.python3.7.site-packages.serial', 'venv.lib.python3.7.site-packages.serial.tools',
              'venv.lib.python3.7.site-packages.serial.threaded', 'venv.lib.python3.7.site-packages.serial.urlhandler',
              'venv.lib.python3.7.site-packages.certifi', 'venv.lib.python3.7.site-packages.chardet',
              'venv.lib.python3.7.site-packages.chardet.cli', 'venv.lib.python3.7.site-packages.geojson',
              'venv.lib.python3.7.site-packages.seaborn', 'venv.lib.python3.7.site-packages.seaborn.tests',
              'venv.lib.python3.7.site-packages.seaborn.colors', 'venv.lib.python3.7.site-packages.seaborn.external',
              'venv.lib.python3.7.site-packages.urllib3', 'venv.lib.python3.7.site-packages.urllib3.util',
              'venv.lib.python3.7.site-packages.urllib3.contrib',
              'venv.lib.python3.7.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.urllib3.packages',
              'venv.lib.python3.7.site-packages.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.dateutil', 'venv.lib.python3.7.site-packages.dateutil.tz',
              'venv.lib.python3.7.site-packages.dateutil.parser', 'venv.lib.python3.7.site-packages.dateutil.zoneinfo',
              'venv.lib.python3.7.site-packages.requests', 'venv.lib.python3.7.site-packages.matplotlib',
              'venv.lib.python3.7.site-packages.matplotlib.tri', 'venv.lib.python3.7.site-packages.matplotlib.axes',
              'venv.lib.python3.7.site-packages.matplotlib.cbook', 'venv.lib.python3.7.site-packages.matplotlib.style',
              'venv.lib.python3.7.site-packages.matplotlib.tests', 'venv.lib.python3.7.site-packages.matplotlib.compat',
              'venv.lib.python3.7.site-packages.matplotlib.testing',
              'venv.lib.python3.7.site-packages.matplotlib.testing.jpl_units',
              'venv.lib.python3.7.site-packages.matplotlib.backends',
              'venv.lib.python3.7.site-packages.matplotlib.backends.qt_editor',
              'venv.lib.python3.7.site-packages.matplotlib.sphinxext',
              'venv.lib.python3.7.site-packages.matplotlib.sphinxext.tests',
              'venv.lib.python3.7.site-packages.matplotlib.projections',
              'venv.lib.python3.7.site-packages.mpl_toolkits.tests',
              'venv.lib.python3.7.site-packages.mpl_toolkits.mplot3d',
              'venv.lib.python3.7.site-packages.mpl_toolkits.axes_grid',
              'venv.lib.python3.7.site-packages.mpl_toolkits.axes_grid1',
              'venv.lib.python3.7.site-packages.mpl_toolkits.axisartist'],
    url='',
    license='',
    author='brian.wagner',
    author_email='',
    description=''
)
